name: Build ThunderNanoServicesRDK on MacOS

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  Thunder_MacOS:
    uses: rdkcentral/Thunder/.github/workflows/MacOS build template.yml@master

  ThunderInterfaces_MacOS:
    needs: Thunder_MacOS
    uses: rdkcentral/ThunderInterfaces/.github/workflows/MacOS build template.yml@master

  ThunderNanoServicesRDK_MacOS:
    needs: ThunderInterfaces_MacOS
    uses: WebPlatformForEmbedded/ThunderNanoServicesRDK/.github/workflows/MacOS build template.yml@master
